import 'package:strucreport/config/application.dart';
import 'package:strucreport/model/photo_model.dart';

class ReportModel {
  String clientName,
      projectNumber,
      address,
      inspectedBy,
      inspectionType,
      clientBrief,
      propertyType,
      propertyTypeComment,
      presentAtSite,
      presentAtSiteComment,
      personAtSiteComment,
      estimatedConstructionDecadeComment,
      externalWallsConstruction,
      externalWallsConstructionComment,
      roofCovering,
      roomNumber,
      roomNumberComment,
      weather,
      weatherComment,
      propertyOnHillComment,
      chimneyStacksRequireMaintenanceComment,
      observedAnyDislodgedTilesComment,
      observedAnyInternalCracksSmaller3mmComment,
      observedAnyInternalCracksLager3mmComment,
      observedAnyInternalCracksLager10mmComment,
      observedDefectiveMortarJointsComment,
      observedDefectiveBricksComment,
      lintelType,
      lintelTypeComment,
      observedAnyCracksAboveLintelsComment,
      constructionOfFloorsOnGroundFloor,
      constructionOfFloorsOnGroundFloorComment,
      belowAverageGroundFloorComment,
      observedDrainagePavementComment,
      constructionOfFloorsOnFirstFloor,
      constructionOfFloorsOnFirstFloorComment,
      belowAverageFirstFloorComment,
      internalFaceGableWall,
      internalFaceGableWallComment,
      observedBayWindowMovementComment,
      observedJunctionMovementComment,
      roofSaggingComment,
      inspectedAllRoomsComment,
      recordedVideoComment,
      otherInformation,
      observedActiveMovementComment,
      preparedBy,
      checkedBy,
      approvedBy;
  bool anyChimneyStacks,
      chimneyStacksRequireMaintenance,
      internalWallsCoveredInPlaster,
      observedAnyDislodgedTiles,
      observedAnyInternalCracksSmaller3mm,
      observedAnyInternalCracksLager3mm,
      observedAnyInternalCracksLager10mm,
      observedDefectiveMortarJoints,
      observedDefectiveBricks,
      observedAnyCracksAboveLintels,
      belowAverageGroundFloor,
      observedDrainagePavement,
      belowAverageFirstFloor,
      observedBayWindowMovement,
      observedJunctionMovement,
      roofSagging,
      inspectedAllRooms,
      recordedVideo,
      observedActiveMovement,
      externalElevations;
  DateTime inspectDate, preparedDate, checkedDate, approvedDate;
  List<PhotoModel> photos;

  ReportModel({
    this.clientName = "",
    this.projectNumber = "",
    this.address = "",
    this.inspectedBy = "Robert Szymborski",
    this.inspectionType = "General Structural Inspection (GSI)",
    this.clientBrief = "The purpose of this report is to provide the client with information regarding the structural condition of the building.",
    this.propertyType = "Detached",
    this.propertyTypeComment = "",
    this.presentAtSite = "Vendor",
    this.presentAtSiteComment = "",
    this.personAtSiteComment = "",
    this.estimatedConstructionDecadeComment = "",
    this.externalWallsConstruction = "Solid",
    this.externalWallsConstructionComment = "",
    this.roofCovering = "Tiles",
    this.roomNumber = "1-Bedroom property",
    this.roomNumberComment = "",
    this.weather = "Overcast",
    this.weatherComment = "",
    this.propertyOnHillComment = "",
    this.chimneyStacksRequireMaintenanceComment = "",
    this.observedAnyDislodgedTilesComment = "There did not appear to be any significantly dislodged tiles/slates, but periodic maintenance work is recommended, a roofing contractor should be consulted for further advice.",
    this.observedAnyInternalCracksSmaller3mmComment = "",
    this.observedAnyInternalCracksLager3mmComment = "",
    this.observedAnyInternalCracksLager10mmComment = "",
    this.observedDefectiveMortarJointsComment = "",
    this.observedDefectiveBricksComment = "",
    this.lintelType = "(a) Likely timber w/arch",
    this.lintelTypeComment = "",
    this.observedAnyCracksAboveLintelsComment = "",
    this.constructionOfFloorsOnGroundFloor = "Suspended",
    this.constructionOfFloorsOnGroundFloorComment = "",
    this.belowAverageGroundFloorComment = "",
    this.observedDrainagePavementComment = "",
    this.constructionOfFloorsOnFirstFloor = "Timber",
    this.constructionOfFloorsOnFirstFloorComment = "",
    this.belowAverageFirstFloorComment = "",
    this.internalFaceGableWall = "Load bearing masonry",
    this.internalFaceGableWallComment = "",
    this.observedBayWindowMovementComment = "",
    this.observedJunctionMovementComment = "",
    this.roofSaggingComment = "",
    this.inspectedAllRoomsComment = "",
    this.recordedVideoComment = "",
    this.otherInformation = "",
    this.observedActiveMovementComment = "",
    this.preparedBy = "Robert Szymborski",
    this.checkedBy = "Robert Szymborski",
    this.approvedBy = "Robert Szymborski",
    this.anyChimneyStacks = false,
    this.chimneyStacksRequireMaintenance = false,
    this.internalWallsCoveredInPlaster = false,
    this.observedAnyDislodgedTiles = false,
    this.observedAnyInternalCracksSmaller3mm = false,
    this.observedAnyInternalCracksLager3mm = false,
    this.observedAnyInternalCracksLager10mm = false,
    this.observedDefectiveMortarJoints = false,
    this.observedDefectiveBricks = false,
    this.observedAnyCracksAboveLintels = false,
    this.belowAverageGroundFloor = false,
    this.observedDrainagePavement = false,
    this.belowAverageFirstFloor = false,
    this.observedBayWindowMovement = false,
    this.observedJunctionMovement = false,
    this.roofSagging = false,
    this.inspectedAllRooms = false,
    this.recordedVideo = false,
    this.observedActiveMovement = false,
    this.externalElevations = false,
    this.inspectDate,
    this.preparedDate,
    this.checkedDate,
    this.approvedDate,
    this.photos
});
}
